(deftheme wheatgrass-mod
  "Created 2013-07-01.")

(custom-theme-set-faces
 'wheatgrass-mod
 '(cursor ((t (:background "DarkGoldenrod4"))))
 '(error ((t (:foreground "orange red"))))
 '(warning ((t (:foreground "orange"))))
 '(success ((t (:foreground "lawn green"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "dark green"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "dark goldenrod"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "SpringGreen4"))))
 '(highlight ((t (:background "dark red" :foreground "white smoke"))))
 '(region ((((class color) (min-colors 89)) (:foreground "white" :background "dark green"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "dark slate gray"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "white" :background "dark goldenrod"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "gray25"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightSteelBlue"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "SpringGreen3"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "turquoise"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "white"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "aquamarine"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "cyan"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "dark cyan"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:weight normal :foreground "yellow green"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "pale turquoise"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "dark sea green"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "dark turquoise"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "pale turquoise"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "SpringGreen3"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "deep sky blue"))))
 '(default ((t (:background "black" :foreground "white")))))

(provide-theme 'wheatgrass-mod)
